"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
//FM();
//AF();
//Prototype();
//Singleton();
//Builder();
//Adapter();
//Bridge();
//Decorator();
//Proxy();
//Facade();
//ChainofResponsability();
//Command();
//Iterator();
//Memento();
//Observer();
//State();
//strategy();
//Template();
